### ISSUE TITLE
Camera / Streaming Control window isn't rotatable

### ISSUE THREAD

**Issue by XDelta** [rampa3/3DDashOnScreen#2]
The Camera / Streaming control window appears to rotation locked in the orientation it gets spawned in. All the other userspace windows I have tried appear to be able to rotate freely.

**Comment by rampa3** [comment]
FIXED: Restored VR behaviour of the camera controls UI - can be moved same as dash in freeform mode - UI always faces user, can be slided around user and moved further or closer in relation to user. If normal, non slider UI is the request, please split off into separate issue.
