### ISSUE TITLE
UI Edit Mode hotkey appears to trigger multiple times

### ISSUE THREAD

**Issue by XDelta** [rampa3/3DDashOnScreen#3]
Using the UI Edit Mode hotkey, sometimes it appears to not switch into or out of edit mode. This seems to be from getting the key every update and triggering rapidly. So it appears to work fine on an odd update count and do nothing on an even update count as it returns to the same state it was just was at.

**Comment by rampa3** [comment]
FIXED! + as bonus, the key is now user selectable in mod config.
