### ISSUE TITLE
Screen randomly whiteouts if in local home

### ISSUE THREAD

**Issue by TisFoolish** [rampa3/3DDashOnScreen#4]
I have noticed that if I'm in my local world (eg by using `-DontAutoOpenCloudHome`) and am using this mod my entire screen will randomly turn white, preventing me from being able to interact with anything. I have not been able to find a way to clear the screen other than already be in the process of joining a world when it happens or restarting Neos.  Even then, if I go back to my local world the screen will still turn white, requiring me to restart Neos. If I leave the local world then come back later, there seems to be a really good chance that upon switching to it my screen will turn white near instantly.

I'm on desktop and I haven't been able to test if this also affects VR yet because my headset is being RMA'd

This happens with the latest version of the 3DDashOnScreen mod and the last two versions.

Running Win 10, tested without mods and just this mod.

**Comment by rampa3** [comment]
As discussed in Discord before, this might be a Neos bug. Since there was no new info for a long time, I will close the issue for now. If new intel is obtained, it will be re-opened.
